"""Compute, per design point, how many statements already exist, how many of
those are actually scored by this dashboard, and how many generated-and-judged
candidates from .scripts/statement-generation/ are ready to supplement them.

Backs the "Design Point Coverage" page (linked from the Design Points panel as
"Explore proposed statements"), served at /statement_generation.

"Existing"/"Published" counts come from the live top-level statements/ +
statementproperties/ tables (see .scripts/statement-generation/gap_analysis.py
for the verified property-name mapping).

"Calculated" counts replicate get_design_points() in server.py exactly (this
app's own answers.csv INNER-joined to crt_rme_demo.csv, statements needing
>= 10 ratings via statement_commonsensicality, tagged via this app's own
statement_properties.csv snapshot) so the number matches the Design Points
panel itself, snapshot staleness and all.

A generated statement is "supplementable" for its design point if at least one
judge model rated it commonsense=1 AND agreed with the generator on all six
features. A statement generated by more than one model, or judged by more than
one qualifying judge, is counted once (by exact statement text) but keeps every
qualifying judge's assessment for the detail view.

The generation pipeline itself (generate.py/judge.py and their prompt/data
files) lives in .scripts/statement-generation/; only this aggregation and its
web presentation live here.
"""
import itertools
import os
import sys
from pathlib import Path

import pandas as pd
import yaml

from utils import statement_commonsensicality

VISUALIZE_DIR = Path(__file__).resolve().parent
# Default to the in-repo sibling directory for local dev; override with
# STATEMENT_GEN_DIR (e.g. in the Docker image, which vendors this flat rather
# than preserving the repo's directory nesting).
STATEMENT_GEN_DIR = Path(os.environ.get("STATEMENT_GEN_DIR", VISUALIZE_DIR.parent / "statement-generation"))
if str(STATEMENT_GEN_DIR) not in sys.path:
    sys.path.insert(0, str(STATEMENT_GEN_DIR))
import gap_analysis  # noqa: E402

# Read feature_definitions straight out of prompt.yml rather than importing
# generate.py for it: generate.py pulls in the full generation pipeline's
# dependencies (openai, jsonschema, json-repair, tqdm, requests, dotenv), none
# of which this read-only aggregation needs.
with (STATEMENT_GEN_DIR / "prompt.yml").open(encoding="utf-8") as _handle:
    FEATURE_DEFINITIONS = yaml.safe_load(_handle)["feature_definitions"]

FEAT_KEYS = [pair.split("/")[0] for pair in FEATURE_DEFINITIONS]
POLE_ZERO = {}
for pair, choices in FEATURE_DEFINITIONS.items():
    key = pair.split("/")[0]
    POLE_ZERO[key] = next(name for name in choices if name != key)


def _judge_value(classification, key):
    """Map a judge's classification string to 0/1 for this feature, or None if unrecognized."""
    c = str(classification).strip().lower()
    if c == key:
        return 1
    if c == POLE_ZERO[key]:
        return 0
    return None


def _existing_by_combo() -> dict:
    props = gap_analysis.load_wide_properties()
    statements = pd.read_csv(
        gap_analysis.REPO_ROOT / "statements" / "statements_1.csv", usecols=["id", "statement", "published"]
    )
    merged = statements.merge(props, left_on="id", right_on="statementId", how="left")
    merged = merged.dropna(subset=FEAT_KEYS)
    for col in FEAT_KEYS:
        merged[col] = merged[col].astype(int)

    by_combo = {}
    for combo in itertools.product([0, 1], repeat=len(FEAT_KEYS)):
        mask = pd.Series(True, index=merged.index)
        for col, val in zip(FEAT_KEYS, combo):
            mask &= merged[col] == val
        by_combo[combo] = [
            {"id": int(row["id"]), "statement": row["statement"], "published": int(row["published"])}
            for _, row in merged[mask].iterrows()
        ]
    return by_combo


def _calculated_by_combo() -> dict:
    """Statements per design point that clear this dashboard's own >=10-rating bar."""
    data_dir = VISUALIZE_DIR / "data"
    answers = pd.read_csv(data_dir / "answers.csv", usecols=["sessionId", "statementId", "I_agree", "others_agree"])
    demo = pd.read_csv(data_dir / "crt_rme_demo.csv", usecols=["sessionId", "country_reside"])
    stmt_props = pd.read_csv(data_dir / "statement_properties.csv")
    statements = pd.read_csv(
        gap_analysis.REPO_ROOT / "statements" / "statements_1.csv", usecols=["id", "statement", "published"]
    ).rename(columns={"id": "statementId"})

    merged = answers.merge(demo, on="sessionId", how="inner")
    ratings = merged[["statementId", "I_agree", "others_agree"]]
    scores = statement_commonsensicality(ratings)
    scores = scores.join(stmt_props.set_index("statementId")[FEAT_KEYS], how="left")
    scores = scores.dropna(subset=FEAT_KEYS)
    for col in FEAT_KEYS:
        scores[col] = scores[col].astype(int)
    scores = scores.reset_index().merge(statements, on="statementId", how="left")

    by_combo = {}
    for combo in itertools.product([0, 1], repeat=len(FEAT_KEYS)):
        mask = pd.Series(True, index=scores.index)
        for col, val in zip(FEAT_KEYS, combo):
            mask &= scores[col] == val
        by_combo[combo] = [
            {
                "id": int(row["statementId"]),
                "statement": row["statement"] if pd.notna(row["statement"]) else "(statement text unavailable)",
                "n_ratings": int(row["n_ratings"]),
                "commonsensicality": round(float(row["commonsensicality"]), 4),
                "published": int(row["published"]) if pd.notna(row["published"]) else 0,
            }
            for _, row in scores[mask].iterrows()
        ]
    return by_combo


def _qualifying_by_combo() -> dict:
    """combo -> {statement_text: entry} where entry has gen_model/gen_features/judges."""
    by_combo = {}
    for gen_path in sorted((STATEMENT_GEN_DIR / "data").glob("*/statements.csv")):
        if not gen_path.stat().st_size:
            continue
        gen_df = pd.read_csv(gen_path)
        if gen_df.empty or not set(FEAT_KEYS).issubset(gen_df.columns):
            continue
        gen_model = gen_path.parent.name.replace("--", "/")
        gen_df = gen_df.reset_index(drop=True)
        gen_df["_source_row"] = gen_df.index + 1

        # source_row -> list of qualifying judge dicts; separately, how many judges
        # were tried at all (pass or fail) so the UI can show "3 / 4 judges".
        judge_hits: dict[int, list] = {}
        judges_tried: dict[int, int] = {}
        for judge_path in sorted(gen_path.parent.glob("evaluations/*/statements.csv")):
            if not judge_path.stat().st_size:
                continue
            try:
                judge_df = pd.read_csv(judge_path)
            except (pd.errors.ParserError, pd.errors.EmptyDataError):
                continue
            if judge_df.empty:
                continue
            for _, jrow in judge_df.iterrows():
                src_row = int(jrow["source_row"])
                if src_row - 1 >= len(gen_df):
                    continue
                grow = gen_df.iloc[src_row - 1]
                if grow["statement"] != jrow["statement"]:
                    continue  # source row was edited since this evaluation ran
                judges_tried[src_row] = judges_tried.get(src_row, 0) + 1
                if int(jrow.get("commonsense", 0)) != 1:
                    continue
                if not all(_judge_value(jrow[f"{key}_classification"], key) == int(grow[key]) for key in FEAT_KEYS):
                    continue
                judge_hits.setdefault(src_row, []).append({
                    "judge_model": jrow["judge_model"],
                    "commonsense_explanation": str(jrow.get("commonsense_explanation", "")),
                    "features": {
                        key: {
                            "classification": jrow[f"{key}_classification"],
                            "confidence": int(jrow[f"{key}_confidence"]),
                            "explanation": str(jrow[f"{key}_explanation"]),
                        }
                        for key in FEAT_KEYS
                    },
                })

        for src_row, judges in judge_hits.items():
            grow = gen_df.iloc[src_row - 1]
            combo = tuple(int(grow[key]) for key in FEAT_KEYS)
            statement_text = grow["statement"]
            entry = {
                "statement": statement_text,
                "gen_model": gen_model,
                "gen_commonsense_explanation": str(grow.get("commonsense", "")),
                "gen_features": {
                    key: {
                        "confidence": int(grow[f"{key}_confidence"]),
                        "explanation": str(grow[f"{key}_explanation"]),
                    }
                    for key in FEAT_KEYS
                },
                "judges": judges,
                "n_judges_tried": judges_tried.get(src_row, len(judges)),
            }
            bucket = by_combo.setdefault(combo, {})
            existing_entry = bucket.get(statement_text)
            if existing_entry is None:
                bucket[statement_text] = entry
            else:
                # Same text supplementable via more than one generator/judge pairing: merge judges.
                existing_entry["judges"].extend(judges)
                existing_entry["n_judges_tried"] += entry["n_judges_tried"]
    return by_combo


_cache = None


def get_coverage() -> dict:
    global _cache
    if _cache is not None:
        return _cache

    existing_by_combo = _existing_by_combo()
    calculated_by_combo = _calculated_by_combo()
    qualifying = _qualifying_by_combo()

    rows = []
    for combo in itertools.product([0, 1], repeat=len(FEAT_KEYS)):
        existing_entries = existing_by_combo.get(combo, [])
        rows.append({
            **dict(zip(FEAT_KEYS, combo)),
            "existing": len(existing_entries),
            "published": sum(1 for s in existing_entries if s["published"]),
            "calculated": len(calculated_by_combo.get(combo, [])),
            "supplementable": len(qualifying.get(combo, {})),
        })

    _cache = {
        "feature_keys": FEAT_KEYS,
        "rows": rows,
        "existing_by_combo": existing_by_combo,
        "calculated_by_combo": calculated_by_combo,
        "qualifying": qualifying,
    }
    return _cache


def get_statements_for_combo(combo: tuple, metric: str) -> list:
    data = get_coverage()
    if metric == "existing":
        return data["existing_by_combo"].get(combo, [])
    if metric == "published":
        return [s for s in data["existing_by_combo"].get(combo, []) if s["published"]]
    if metric == "calculated":
        return data["calculated_by_combo"].get(combo, [])
    if metric == "supplementable":
        return list(data["qualifying"].get(combo, {}).values())
    raise ValueError(f"Unknown metric: {metric!r}")
